# version: '3.1'

services:
  server:
    image: ${IMAGE_REPOSITORY:-ghcr.io/acehubert/pomelo:latest}
    container_name: pomelo-server
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    environment:
      - SWAGGER_DEBUG=${SWAGGER_DEBUG:-false}
      - GRAPHQL_DEBUG=${GRAPHQL_DEBUG:-false}
      - ORIGIN=${ORIGIN:-https://example.com}
      - REDIS_URL=redis://redis:6379/0
      - INFRASTRUCTURE_DATABASE_CONNECTION=mysql://${MYSQL_USER:-pomelo}:${MYSQL_PASSWORD}@mysql:3306/${INFRASTRUCTURE_DATABASE_NAME:-po_template}
      - IDENTITY_DATABASE_CONNECTION=mysql://${MYSQL_USER:-pomelo}:${MYSQL_PASSWORD}@mysql:3306/${IDENTITY_DATABASE_NAME:-po_identity}
      - TABLE_PREFIX=${TABLE_PREFIX:-po_}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ${PWD}/conf:/app/conf
      - ${PWD}/uploads:/app/content/uploads
      - ${PWD}/plugins:/app/content/plugins
      - ${PWD}/themes:/app/content/themes
      - ${PWD}/logs:/app/logs
    privileged: true
    # ports:
      # - 3000:3000 # web
      # - 3002:3002 # bff server
      # - 3003:3003 # identity server
      # - 3004:3004 # static content
    external_links:
      - ${MYSQL_CONTAINER_NAME:-mysql}:mysql
      - ${REDIS_CONTAINER_NAME:-redis}:redis
    networks:
      - default
      - mysql
      - redis
  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.13.0-debian}
    container_name: pomelo-apisix
    restart: always
    environment:
      - APISIX_STAND_ALONE=true
    volumes:
      - ${PWD}/apisix/conf/apisix-standalone.yaml:/usr/local/apisix/conf/apisix.yaml:ro
      - ${PWD}/apisix/conf/config-standalone.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ${PWD}/apisix:/usr/local/apisix/logs
    privileged: true
    depends_on:
      - server
    ##network_mode: host
    # ports:
      # - '9180:9180/tcp' # admin_control: true
      # - '9080:9080/tcp'  # http
      # - '9091:9091/tcp'  # prometheus
      # - '9443:9443/tcp'  # tls http/2
      # - '9092:9092/tcp' # enable_control: true
    networks:
      - default
  nginx:
    image: nginx:${NGINX_IMAGE_TAG:-alpine}
    container_name: pomelo-nginx
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/nginx:/var/log/nginx
    ports:
      - '8080:80'
      - '8443:443'
    depends_on:
      - server
      - apisix
    networks:
      - default
networks:
  mysql:
    name: ${MYSQL_NETWORK_NAME:-mysql_default}
    external: true
  redis:
    name: ${REDIS_NETWORK_NAME:-redis_default}
    external: true
# volumes:
#   conf:
#    name: pomelo-conf
#     driver: local
#     driver_opts:
#       type: none
#       device: ${PWD}/${CONF_DIR:-conf}
#       o: bind
