# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:

# >  cat > .env.docker.local
# // Apple M1
# BUILD_PLATFORM=linux/arm64/v8
# BUILD_TAG=0.0.1
# BUILD_IGNORE=true
# BUILD_OPTION=build:local
# RUNTIME_ENV=production
# SERVE_ENV=local
# SERVE_APPS=''


# > rm -rf release && mkdir release && docker compose --env-file .env.docker.local up --build --force-recreate  -d

version: '3.1'

networks:
  mysql_default:
    external: true
  redis_default:
    external: true
services:
  server:
    build:
      context: ${BUILD_CONTEXT:-.}
      dockerfile: Dockerfile
      args:
        BUILD_PLATFORM: ${BUILD_PLATFORM:-linux/amd64}
        BUILD_IGNORE: ${BUILD_IGNORE:-false}
        BUILD_OPTION: ${BUILD_OPTION:-vue}
        RUNTIME_ENV: ${RUNTIME_ENV:-production}
        SERVE_ENV: ${SERVE_ENV:-production}
        SERVE_APPS: ${SERVE_APPS}
        BUILDKIT_INLINE_CACHE: true
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: true
      cache_from:
        - pomelo:latest
      target: deploy
      tags:
        - pomelo:${BUILD_TAG:-latest}
    image: pomelo
    container_name: pomelo-server
    restart: always
    ports:
      - 3001:3001
      - 3002:3002
      - 3003:3003
      - 3011:3011
      - 3012:3012
    volumes:
      - deploy:/app
    external_links:
      - mysql-default-5.7:mysql
      - redis-default-6.2:redis
    networks:
      - default
      - mysql_default
      - redis_default
volumes:
  deploy:
    name: pomelo
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/${DEPLOY_DIR:-release}
      o: bind
