# https://fly.io/docs/app-guides/mysql-on-fly/

# fly volumes create mysqldata --size 1 # gb
# fly secrets set MYSQL_PASSWORD=passw0rd@123 MYSQL_ROOT_PASSWORD=passw0rd@123
# fly deploy --config fly.mysql.toml

app = "pomelo-mysql"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"
processes = []

[mounts]
  source="mysqldata"
  destination="/data"

[env]
  MYSQL_DATABASE = "M_Template"
  MYSQL_USER = "pomelo"


[build]
  image = "mysql:5.7"

[experimental]
  cmd = [
    "--default-authentication-plugin",
    "mysql_native_password",
    "--datadir",
    "/data/mysql"
  ]
