# https://fly.io/docs/reference/monorepo/

# fly volumes create myuploadsdata --size 1 # gb
# fly secrets set DATABASE_CONNECTION=mysql://pomelo:passw0rd@123@pomelo-mysql.internal/M_Template AUTH_ENDPOINT=https://demo.login.ihealthinkcare.com/
# fly deploy --config fly.backend.toml --dockerfile ./Dockerfile.backend

app = "pomelo-backend"
primary_region = "nrt"

[mounts]
source="myuploadsdata"
destination="/content/upload"

[env]
  NODE_ENV = "production"
  ENV_FILE = ".env.fly"
