# https://fly.io/docs/reference/monorepo/

# fly volumes create myuploadsdata --size 1 # gb
# fly secrets set DATABASE_CONNECTION=mysql://pomelo:passw0rd@123@pomelo-mysql.internal/M_Template AUTH_ENDPOINT=https://auth.pomelo.com/
# fly deploy --config fly.infrastructure-api.toml --dockerfile ./Dockerfile.infrastructure-api

app = "infrastructure-api"
primary_region = "nrt"

[mounts]
source="myuploadsdata"
destination="/content/upload"

[env]
  NODE_ENV = "production"
  ENV_FILE = ".env.fly"
