// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: common/meta.proto

/* eslint-disable */

export const protobufPackage = 'pomelo.service';

/** MetaModel 表示元数据信息 */
export interface MetaModel {
  /** 元数据的唯一标识符 */
  id: number;
  /** 元数据的键 */
  metaKey: string;
  /** 元数据的值，可以为空 */
  metaValue?: string | undefined;
}

/** GetMetaRequest 表示获取元数据的请求 */
export interface GetMetaRequest {
  /** 要获取的元数据的唯一标识符 */
  id: number;
  /** 要获取的字段列表 */
  fields: string[];
}

/** CreateMetaRequest 表示创建新元数据的请求 */
export interface CreateMetaRequest {
  /** 新元数据的键 */
  metaKey: string;
  /** 新元数据的值，可以为空 */
  metaValue?: string | undefined;
}

/** UpdateMetaRequest 表示更新现有元数据的请求 */
export interface UpdateMetaRequest {
  /** 要更新的元数据的唯一标识符 */
  id: number;
  /** 要设置的新值 */
  metaValue: string;
}

/** DeleteMetaRequest 表示删除元数据的请求 */
export interface DeleteMetaRequest {
  /** 要删除的元数据的唯一标识符 */
  id: number;
}

export const POMELO_SERVICE_PACKAGE_NAME = 'pomelo.service';
