// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: common/shared.proto

/* eslint-disable */

export const protobufPackage = 'pomelo.service';

/** IdRequest 表示包含ID参数的请求 */
export interface IdRequest {
  /** 唯一标识符 */
  id: number;
}

/** RequestUserIdRequest 表示包含用户ID参数的请求 */
export interface RequestUserIdRequest {
  /** 发起请求的用户ID */
  requestUserId: number;
}

export const POMELO_SERVICE_PACKAGE_NAME = 'pomelo.service';
