export const AUTHORIZATION_KEY = '__AUTHORIZATION_KEY__';
export const AUTHORIZATION_ROLE_KEY = '__AUTHORIZATION_ROLE_KEY__';
export const AUTHORIZATION_RAM_ACTION_KEY = '__AUTHORIZATION_RAM_ACTION_KEY__';
export const ALLOWANONYMOUS_KEY = '__ALLOWANONYMOUS_KEY__';
