// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: index.proto

/* eslint-disable */

export const protobufPackage = 'pomelo.service';

export const POMELO_SERVICE_PACKAGE_NAME = 'pomelo.service';
