// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: site-init.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { Empty } from './google/protobuf/empty';
import { BoolValue } from './google/protobuf/wrappers';

export const protobufPackage = 'pomelo.service';

/**
 * 站点初始化配置请求
 * 用于首次启动时配置站点的基本信息
 */
export interface StartOptionRequest {
  /** 站点标题 */
  title: string;
  /** 管理员初始密码 */
  password: string;
  /** 管理员电子邮箱 */
  email: string;
  /** web端访问地址 */
  homeUrl: string;
  /** 静态资源地址 */
  siteUrl: string;
  /** 默认语言设置 */
  locale: string;
}

export const POMELO_SERVICE_PACKAGE_NAME = 'pomelo.service';

/**
 * 站点初始化服务接口定义
 * 用于处理站点的首次初始化流程
 */

export interface SiteInitServiceClient {
  /** 检查是否需要初始化站点 */

  isRequired(request: Empty, ...rest: any): Observable<BoolValue>;

  /** 开始执行站点初始化 */

  start(request: StartOptionRequest, ...rest: any): Observable<Empty>;
}

/**
 * 站点初始化服务接口定义
 * 用于处理站点的首次初始化流程
 */

export interface SiteInitServiceController {
  /** 检查是否需要初始化站点 */

  isRequired(request: Empty, ...rest: any): Promise<BoolValue> | Observable<BoolValue> | BoolValue;

  /** 开始执行站点初始化 */

  start(request: StartOptionRequest, ...rest: any): void;
}

export function SiteInitServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['isRequired', 'start'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      if (descriptor) {
        GrpcMethod('SiteInitService', method)(constructor.prototype[method], method, descriptor);
      }
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('SiteInitService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SITE_INIT_SERVICE_NAME = 'SiteInitService';
