# swagger configuration
swagger:
  # show swagger documentation
  debug: true
  # swagger path
  # path: "/doc"
# graphql configuration
graphql:
  # show graphql playground
  debug: true
  # graphql path
  # path: "/graphql"
# server configuration
# server:
  # cors:
  #   - "*"
  # credentials: true
# upload configuration
# upload:
#   # upload path
#   dest: "./content"
#   # upload file size limit, a byte number,
#   # or string(https://github.com/visionmedia/bytes.js), default: 10MB
#   maxFileSize: 1000000
#   # upload file count limit, default: 10
#   maxFiles: 10
# redis connection, from fly secrets
# REDIS_URL: "redis://host:port/db"
# infrastructure database connection, from fly secrets
# INFRASTRUCTURE_DATABASE_CONNECTION: "mysql://user:password@host:port/database"
# identity database connection, from fly secrets
# IDENTITY_DATABASE_CONNECTION: "mysql://user:password@host:port/database"
# table prefix
# TABLE_PREFIX: "po_"
# set web oidc redirect uris, default: ${server.origin}
WEB_URL: "https://pomelo-client.fly.dev:3011"
